version: '3.7'

networks:
  my_network:
    name: my_network
    #    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16


services:

#  etcd:
#    image: 'bitnami/etcd:latest'
#    container_name: etcd
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
#    ports:
#      - "2379:2379"
#      - "2380:2380"
#      - "4001:4001"
#    networks:
#      - my_network

  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    command: mongod --wiredTigerCacheSizeGB 25 --bind_ip_all --replSet rs0 # 单节点复制集
    networks:
      - my_network
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis
    volumes:
      #      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./data/redis:/data
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

#  pika:
#    image: "pikadb/pika:latest"
#    container_name: pika
#    ports:
#      - "9221:9221"
#    volumes:
#      - ./data/pika:/pika/log
#      # Specify the configuration file path. If you need to specify a configuration file, specify it here.
#      # Note: pika.conf should be in the ./deploy/pika directory
#      - ./deploy/pika:/pika/conf
#      - ./data/pika/db:/pika/db
#      - ./data/pika/dump:/pika/dump
#      - ./data/pika/dbsync:/pika/dbsync
#      - ./data/pika/pid/:/pika/pid
#    privileged: true
#    restart: always
#    networks:
#      - my_network

#  ledis:
#    image: "expert/ledisdb:6.6.4"
#    container_name: ledis
#    ports:
#      - "6380:6380"
#      - "11181:11181"
#    volumes:
#      - ./deploy/ledis/ledisdb.conf:/etc/ledisdb.conf
#      - ./data/ledis:/data
#    privileged: true
#    restart: always
#    networks:
#      - my_network

  kvrocks:
    image: "apache/kvrocks:latest"
    container_name: kvrocks
    ports:
      - "6666:6666"
    volumes:
#      - ./deploy/kvrocks/kvrocks.conf:/var/lib/kvrocks/kvrocks.conf
#      - ./data/kvrocks:/var/lib/kvrocks
      - ./data/kvrocks/db:/var/lib/kvrocks/db
#      - ./data/kvrocks/thebestdbname:/var/lib/kvrocks/thebestdbname
      - ./data/kvrocks/backup:/var/lib/kvrocks/backup
#      - ./data/kvrocks/kvrocks.pid:/var/run/kvrocks/kvrocks.pid
    privileged: true
    restart: always
    networks:
      - my_network


  tendis:
    image: "tencentdbforkv/tendisplus"
    container_name: tendis
    ports:
      - "51002:51002"
    volumes:
#      - ./deploy/tendis/tendis.conf:/data1/tendis/scripts/tendis.conf
      - ./data/tendis/db:/data1/tendis/51002/db
      - ./data/tendis/log:/data1/tendis/51002/log
      - ./data/tendis/dump:/data1/tendis/51002/dump
    privileged: true
    restart: always
    networks:
      - my_network




